// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2B0OEZ_nAZytgAsyaxLy0U5g0rZCm00U',
    appId: '1:326811145913:web:b9c630cf5af1c7a32d2d68',
    messagingSenderId: '326811145913',
    projectId: 'fkrapp-3',
    authDomain: 'fkrapp-3.firebaseapp.com',
    databaseURL: 'https://fkrapp-3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fkrapp-3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn3MZFn7SX_ut8o2a47JKgIYLguaauXZ8',
    appId: '1:326811145913:android:8ed9fb4b2ee7792d2d2d68',
    messagingSenderId: '326811145913',
    projectId: 'fkrapp-3',
    databaseURL: 'https://fkrapp-3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fkrapp-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJFYM_y3t6P5WXqYSWVFw4UAtaP_DLgUE',
    appId: '1:326811145913:ios:ccf3fc0fdb9778352d2d68',
    messagingSenderId: '326811145913',
    projectId: 'fkrapp-3',
    databaseURL: 'https://fkrapp-3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fkrapp-3.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJFYM_y3t6P5WXqYSWVFw4UAtaP_DLgUE',
    appId: '1:326811145913:ios:8b8d4e48ffd824ca2d2d68',
    messagingSenderId: '326811145913',
    projectId: 'fkrapp-3',
    databaseURL: 'https://fkrapp-3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fkrapp-3.appspot.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
